import Advantages from "@/components/advantages/Advantages";
import Banner from "@/components/banner/Banner";
import MainLayout from "@/layouts/main.layout";
import Head from "next/head";
import Cars from "@/components/cars/Cars";
import Process from "@/components/process/Process";
import Calculate from "@/components/calculate/Calculate";
import FAQ from "@/components/faq/Faq";
import Form from "@/components/form/Form";
import Contact from "@/components/contact/Contact";
import Test from "@/components/testkeus/Testkeys";

export default function Home() {
  return (
    <>
      <Head>
        <title>Импорт авто из Казахстана | КазТрейд</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <MainLayout>
        <Banner/>
        <Advantages/>
        <Cars/>
        <Process/>
        <Calculate/>
        <FAQ/>
        <Form/>
        <Contact/>
        {/* <Test/> */}
      </MainLayout>
    </>
  );
}
